knp_paginator:
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Use Bootstrap 5 pagination template
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'